const MODAL_BODY_TYPES = {
  USER_DETAIL: 'USER_DETAIL',
  LEAD_ADD_NEW: 'LEAD_ADD_NEW',
  DEFAULT: '',
};

const RIGHT_DRAWER_TYPES = {
  NOTIFICATION: 'NOTIFICATION',
  DEFAULT: '',
};

export { MODAL_BODY_TYPES, RIGHT_DRAWER_TYPES };
