name: Deploy specific version to S3

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version(Tag Name)'
        required: true

jobs:
  restartContainer:
    name: Update Nginx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for Tag
        run: |
          TAG="${{ github.event.inputs.version }}"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} exists"
          else
            echo "Tag ${TAG} does not exist"
            exit 1
          fi
      - name: Update nginx.conf
        run: |
          sed -i 's/\$VERSION/${{ github.event.inputs.version }}/g' ./nginx/nginx-s3.conf
      - name: Copy nginx.confg via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./nginx/nginx-s3.conf
          target: ~/aki_erp_config/
          overwrite: true
      - name: Restart nginx container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop aki-erp 2> /dev/null
            docker rm aki-erp 2> /dev/null
            docker run -d --name aki-erp -v ~/aki_erp_config/nginx/nginx-s3.conf:/etc/nginx/conf.d/default.conf -p 18888:80 nginx:stable-alpine
